name: CI

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Set release name
      run: |
        $RELEASE = cat $Env:GITHUB_EVENT_PATH | jq --raw-output .release.id
        echo "releaseID=$RELEASE" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "fileName=dap-${{ github.event.release.tag_name }}-win64" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.1
        pip install -r build/requirements.txt

    - name: Compile to exe
      run: |
        pyinstaller ./build/main.spec

    - name: Release
      run: | 
        $uploadPath = "./dist/dap.exe"
        $uri = "https://uploads.github.com/repos/$Env:GITHUB_REPOSITORY/releases/${{ env.releaseID }}/assets?name=${{ env.fileName }}.exe"
        $headers = @{"Content-Type"="application/x-msdownload"; "Authorization"="token ${{ secrets.GITHUB_TOKEN }}"}
        Invoke-WebRequest -Uri $uri -Method POST -Header $headers -InFile $uploadPath
