name: CI

on:
  release:
    types: [prereleased, published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install python dependencies
      run: |
        c:\hostedtoolcache\windows\python\3.7.9\x64\python.exe -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Compile to exe
      run: pyinstaller --name dap --onefile ./build/main.spec

    - name: Release
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        $uploadPath = "./dist/dap.exe"
        $releaseID = cat ${Env:GITHUB_EVENT_PATH} | jq --raw-output .release.id
        $uri = "https://uploads.github.com/repos/${Env:GITHUB_REPOSITORY}/releases/${releaseID}/assets?name=dap.exe"
        $headers = @{"Content-Type"="application/x-msdownload"; "Authorization"="token ${Env:GITHUB_TOKEN}"}
        Invoke-WebRequest -Uri $uri -Method POST -Header $headers -InFile $uploadPath
